apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-app
  labels:
    app: hospital-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hospital-app
  template:
    metadata:
      labels:
        app: hospital-app
    spec:
      containers:
        - name: hospital-app
          image: mahendra310/hospitalmanagement_${BUILD_NUMBER}:latest   # 🔥 replace with your image
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: hospital-app
  labels:
    app: hospital-app
spec:
  type: LoadBalancer
  selector:
    app: hospital-app
  ports:
    - port: 8080
      targetPort: 8080
